# Generated by Django 3.1.2 on 2020-10-24 23:34

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.IntegerField()),
                ('past_temps', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None)),
                ('city', models.TextField(default='Austin')),
            ],
        ),
        migrations.CreateModel(
            name='WeatherRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.BigIntegerField()),
                ('dt', models.BigIntegerField()),
                ('temp', models.IntegerField()),
                ('feels_like', models.IntegerField()),
                ('humidity', models.IntegerField()),
                ('wind_speed', models.IntegerField()),
                ('clouds', models.IntegerField()),
                ('rain', models.IntegerField()),
                ('snow', models.IntegerField()),
                ('rating', models.IntegerField()),
            ],
        ),
    ]
