# Generated by Django 3.1.2 on 2020-10-24 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='past_temps',
        ),
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.BigIntegerField(),
        ),
    ]
