# Generated by Django 3.1.2 on 2020-10-24 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_auto_20201024_2027'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.BigIntegerField()),
                ('dt', models.BigIntegerField()),
                ('temp', models.IntegerField()),
                ('feels_like', models.IntegerField()),
                ('humidity', models.IntegerField()),
                ('wind_speed', models.IntegerField()),
                ('clouds', models.IntegerField()),
                ('rain', models.IntegerField()),
                ('snow', models.IntegerField()),
                ('rating', models.IntegerField()),
            ],
            options={
                'unique_together': {('uuid', 'dt')},
            },
        ),
    ]
