# Generated by Django 3.1.2 on 2020-10-24 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0003_weatherrating'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.TextField(default='Austin'),
        ),
    ]
